---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bf42-servers-backend
  namespace: bf42-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bf42-servers-backend
  template:
    metadata:
      labels:
        app: bf42-servers-backend
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: api
          image: localhost:30500/bf42-servers-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: PROMETHEUS_URL
              value: "http://kube-prometheus-stack-prometheus.monitoring:9090/api/v1"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: bf42-servers-backend-service
  namespace: bf42-servers
spec:
  selector: 
    app: bf42-servers-backend
  type: ClusterIP  
  ports:
    - port: 80
      targetPort: 3000